In [1]:
x_train = [
    [9], [15], [24], [36], [45], [57]
]

y_train = [0, 1, 2, 3, 4, 5]

In [2]:
from sklearn import linear_model
regr = linear_model.LinearRegression()
regr.fit(x_train, y_train)

print(regr.coef_)  

[0.10142349]


In [3]:
import numpy as np
np.mean((regr.predict(x_train) - y_train)**2)

0.026097271648873047

In [4]:
regr.score(x_train, y_train)

0.9910523640061007

In [5]:
np.round(regr.predict(x_train))

array([0., 1., 2., 3., 4., 5.])

In [6]:
np.round(regr.predict([[97]]))

array([9.])

In [7]:
regr.predict([[97]])

array([9.19395018])